
version : '3'

services:
  nginx:
    container_name: c_nginx
    build: nginx/
    image: nginx
    depends_on :
      - wordpress
    restart: always
    ports:
      - "443:443"
    networks:
      - wordpress
    volumes:
      - wp_volume:/var/www/wordpress

  wordpress:
    container_name: c_wordpress
    build: wordpress/
    image: wordpress
    depends_on :
      - mariadb
    restart: always
    networks:
      - wordpress
    env_file:
      - .env
    volumes:
      - wp_volume:/var/www/wordpress

  mariadb:
    container_name: c_mariadb
    build: mariadb/
    image: mariadb
    restart: always
    networks:
      - wordpress
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge

volumes:
    db_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: '/home/kbaek/data/db_data'

    wp_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: '/home/kbaek/data/wp_data'

